### PR TITLE
update chat page 

### PR DESCRIPTION
**Pull request by sheriifMahadi**
Chat page, message pane & info WIP

### CODE REVIEW

**Comment by aminblm** [comment]
Please fix the following errors: 
image

**Comment by aminblm** [comment]
Great!
And amazing job!

**Review by PeaceOloruntoba — APPROVED** [review]
nice work guys

**Comment by sheriifMahadi** [comment]
> nice work guys

Thanks

**Review by PeaceOloruntoba — APPROVED** [review]
good work boss

**Review by aminblm — APPROVED** [review]

**Comment by aminblm** [comment]
Just merged. Great job! Have a look at the chat view. @sheriifMahadi yours is different from the one in the view.

image

**Comment by sheriifMahadi** [comment]
> Just merged. Great job! Have a look at the chat view. @sheriifMahadi yours is different from the one in the view.
> 
> image

Well, it's still WIP. I think they updated the page too. But yeah I'm still working on it.

**Pull request merged**
